# Generated by Django 3.0.2 on 2020-01-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20200109_1833"),
    ]

    operations = [
        migrations.RenameField("Asset", "kind", "type"),
    ]
