# Generated by Django 3.0.2 on 2020-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('CA', 'Cash'), ('BC', 'Bank card'), ('CC', 'Credit card')], max_length=2, verbose_name='Type of asset'),
        ),
    ]
