# Generated by Django 3.0.2 on 2020-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200110_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='incometransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Income money amount'),
        ),
    ]
