# Generated by Django 3.0.2 on 2020-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200113_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Transaction maney amount'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Transaction maney amount'),
        ),
    ]
