# Generated by Django 3.0.3 on 2020-03-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Telegram username')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=2048, verbose_name='User message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tg_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser')),
            ],
        ),
    ]
