# Generated by Django 3.0.3 on 2020-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200309_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='last_login',
            new_name='updated_at',
        ),
    ]
