# Generated by Django 3.0.3 on 2020-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200309_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='is_authenticated',
            new_name='is_active',
        ),
    ]
